########################################################################
--- #LOCAL               
########################################################################
########################################################################
# server Setting
########################################################################
server:
  port: 8080
  servlet:
    context-path: /
########################################################################
# Spring Setting
########################################################################
spring:
  main.allow-bean-definition-overriding: true    
  profiles: local
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/saas/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:4407/localdb_schema1?autoReconnect=true
    url: jdbc:mysql://localhost:4407/localdb_schema1?autoReconnect=true
    username: root
    password: qwQW11!!
##################################################################
# LOGGING LEVELS
##################################################################        
logging:
  config: classpath:logback/logback-spring.xml
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: DEBUG
##################################################################
# ENCRYPT PROPERTIES
##################################################################
jasypt:
  encryptor:
    bean: encryptorBean
##################################################################
# ENCRYPT KEY
##################################################################     
encrypt:
  aeskey: TUNECLOUD SAAS PROVISIONING SYSTEM
##################################################################
# aws defult service endpoint 
##################################################################    
aws:
  endpoint: 
    regionName: us-east-1
##################################################################
# mybatis
##################################################################     
mybatis:
  mapper-locations:
    - classpath:io/tunecloud/**/**/**/dao/sql/**/*.xml
