########################################################################
--- #Dev               
########################################################################
########################################################################
# server Setting
########################################################################
server:
  port: 8080
  servlet:
    context-path: /
########################################################################
# Spring Setting
########################################################################
spring:
  main.allow-bean-definition-overriding: true    
  profiles: dev
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/saas/
##################################################################
# LOGGING LEVELS
##################################################################        
logging:
  config: classpath:logback/logback-spring.xml
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: DEBUG
##################################################################
# ENCRYPT PROPERTIES
##################################################################
jasypt:
  encryptor:
    bean: encryptorBean
##################################################################
# ENCRYPT KEY
##################################################################     
encrypt:
  aeskey: TUNECLOUD SAAS PROVISIONING SYSTEM   
 
